### ISSUE TITLE
能否将select组件的popper-append-to-body设为false

### ISSUE THREAD

**Issue by H-Sven** [ZhenyuCheng/multiCascaderBaseEle#1]
组件中使用到了el-select 组件吧，该组件有个属性   默认是 `popper-append-to-body=“true”`

文档上说明 `是否将弹出框插入至 body 元素。在弹出框的定位出现问题时，可将该属性设置为 false`

我在使用中发现如果宽度不够自动向下展开的时候，位置出现了问题，所以如果将这个值该成false 应该能解决这个问题

**Comment by ZhenyuCheng** [comment]
这个组件不是基于el-select 的，是基于el-cascader，两者关联性不大，el-cascader与el-select使用popper的方式有所差异，如果改成el-select 会比较麻烦，如果不想挂载到body上的话，可以提供一个属性来指定popper的挂载元素

**Comment by ZhenyuCheng** [comment]
> 组件中使用到了el-select 组件吧，该组件有个属性 默认是 `popper-append-to-body=“true”`
> 
> 文档上说明 `是否将弹出框插入至 body 元素。在弹出框的定位出现问题时，可将该属性设置为 false`
> 
> 我在使用中发现如果宽度不够自动向下展开的时候，位置出现了问题，所以如果将这个值该成false 应该能解决这个问题

这个组件不是基于el-select 的，是基于el-cascader，两者关联性不大，el-cascader与el-select使用popper的方式有所差异，如果改成el-select的使用方式会比较麻烦，如果不想挂载到body上的话，我可以提供一个属性来指定popper的挂载元素

**Comment by H-Sven** [comment]
> > 组件中使用到了el-select 组件吧，该组件有个属性 默认是 `popper-append-to-body=“true”`
> > 文档上说明 `是否将弹出框插入至 body 元素。在弹出框的定位出现问题时，可将该属性设置为 false`
> > 我在使用中发现如果宽度不够自动向下展开的时候，位置出现了问题，所以如果将这个值该成false 应该能解决这个问题
> 
> 这个组件不是基于el-select 的，是基于el-cascader，两者关联性不大，el-cascader与el-select使用popper的方式有所差异，如果改成el-select的使用方式会比较麻烦，如果不想挂载到body上的话，我可以提供一个属性来指定popper的挂载元素

你好，这个不支持动态加载子组件吗？

**Comment by ZhenyuCheng** [comment]
支持啊，监听事件就好了@active-item-change="handleItemChange"，不过注意如果异步加载次级选项，最好不要用搜索，搜索只会搜索目前已经拿到的所有选项值

**Comment by ZhenyuCheng** [comment]
> > > 组件中使用到了el-select 组件吧，该组件有个属性 默认是 `popper-append-to-body=“true”`
> > > 文档上说明 `是否将弹出框插入至 body 元素。在弹出框的定位出现问题时，可将该属性设置为 false`
> > > 我在使用中发现如果宽度不够自动向下展开的时候，位置出现了问题，所以如果将这个值该成false 应该能解决这个问题
> > 
> > 
> > 这个组件不是基于el-select 的，是基于el-cascader，两者关联性不大，el-cascader与el-select使用popper的方式有所差异，如果改成el-select的使用方式会比较麻烦，如果不想挂载到body上的话，我可以提供一个属性来指定popper的挂载元素
> 
> 你好，这个不支持动态加载子组件吗？

已支持挂载到指定元素
动态加载子组件原本就是支持的，监听事件就好了@active-item-change="handleItemChange"，不过注意如果异步加载次级选项，最好不要用搜索，搜索只会搜索目前已经拿到的所有选项值

看这个： https://github.com/ZhenyuCheng/multiCascaderBaseEle/issues/3#issuecomment-484787903
