### ISSUE TITLE
样式有问题，样式不支持

### ISSUE THREAD

**Issue by I-really-konw-P** [ZhenyuCheng/multiCascaderBaseEle#11]

**Comment by I-really-konw-P** [comment]
搜索的时候输入有问题，没有显示

**Comment by ZhenyuCheng** [comment]
> 搜索的时候输入有问题，没有显示

已修复

**Comment by fox19920726** [comment]
样式问题：
![image](https://user-images.githubusercontent.com/7921911/58935446-10547b80-87a0-11e9-98b3-8674da8716a5.png)

**Comment by fox19920726** [comment]
> 样式问题：
> ![image](https://user-images.githubusercontent.com/7921911/58935446-10547b80-87a0-11e9-98b3-8674da8716a5.png)

解决了，element-ui的版本问题，降了版本就好了
