### ISSUE TITLE
当设置showAllLevels属性为false时，没有选项时显示undefined/When setting showAllLevels true,if there's no option, placeholder is undefined.

### ISSUE THREAD

**Issue by ZHOUZH1CH3N** [ZhenyuCheng/multiCascaderBaseEle#16]
```html
<el-multi-cascader
                ref="subject"
                class="l-d-no-border"
                style="width: 100%;"
                :placeholder="placeholder"
                :options="options"
                multiple
                :select-children="selectChildren"
                :only-out-put-leaf-node="onlyOutPutLeafNode"
                :collapse-tags="collapseTags"
                :filterable="filterable"
                :show-all-levels="showAllLevels"
                :expand-trigger="expandTrigger"
                :separator="separator"
                :disabled="disabled"
                @change="valueChange"
                :clearable="clearable"
                :change-on-select="changeOnSelect"
                :append-to-body="appendToBody"
                size="medium"
                v-model="checkedSubjects">
</el-multi-cascader>
```
```javascript
      appendToBody: true,
      multiple: true,
      selectChildren: false,
      onlyOutPutLeafNode: false,
      collapseTags: false,
      filterable: false,
      showAllLevels: false,
      expandTrigger: 'hover',
      separator: '-',
      disabled: false,
      clearable: true,
      changeOnSelect: true
```
出现了描述中的问题
![image](https://user-images.githubusercontent.com/17507451/68357269-b80b1680-014f-11ea-8f38-f08940f8f101.png)
在设置showAllLevels为true后，就没有这个问题了，但是需要的是只显示选择的一级。

**Comment by ZhenyuCheng** [comment]
> ```
> <el-multi-cascader
>                 ref="subject"
>                 class="l-d-no-border"
>                 style="width: 100%;"
>                 :placeholder="placeholder"
>                 :options="options"
>                 multiple
>                 :select-children="selectChildren"
>                 :only-out-put-leaf-node="onlyOutPutLeafNode"
>                 :collapse-tags="collapseTags"
>                 :filterable="filterable"
>                 :show-all-levels="showAllLevels"
>                 :expand-trigger="expandTrigger"
>                 :separator="separator"
>                 :disabled="disabled"
>                 @change="valueChange"
>                 :clearable="clearable"
>                 :change-on-select="changeOnSelect"
>                 :append-to-body="appendToBody"
>                 size="medium"
>                 v-model="checkedSubjects">
> </el-multi-cascader>
> ```
> 
> ```js
>       appendToBody: true,
>       multiple: true,
>       selectChildren: false,
>       onlyOutPutLeafNode: false,
>       collapseTags: false,
>       filterable: false,
>       showAllLevels: false,
>       expandTrigger: 'hover',
>       separator: '-',
>       disabled: false,
>       clearable: true,
>       changeOnSelect: true
> ```
> 
> 出现了描述中的问题
> ![image](https://user-images.githubusercontent.com/17507451/68357269-b80b1680-014f-11ea-8f38-f08940f8f101.png)
> 在设置showAllLevels为true后，就没有这个问题了，但是需要的是只显示选择的一级。

https://zhenyucheng.github.io/multiCascaderBaseEle/dist/index.html example中并没有复现这个问题？是否有Demo或者复现步骤？

**Comment by ZHOUZH1CH3N** [comment]
> > ```
> > <el-multi-cascader
> >                 ref="subject"
> >                 class="l-d-no-border"
> >                 style="width: 100%;"
> >                 :placeholder="placeholder"
> >                 :options="options"
> >                 multiple
> >                 :select-children="selectChildren"
> >                 :only-out-put-leaf-node="onlyOutPutLeafNode"
> >                 :collapse-tags="collapseTags"
> >                 :filterable="filterable"
> >                 :show-all-levels="showAllLevels"
> >                 :expand-trigger="expandTrigger"
> >                 :separator="separator"
> >                 :disabled="disabled"
> >                 @change="valueChange"
> >                 :clearable="clearable"
> >                 :change-on-select="changeOnSelect"
> >                 :append-to-body="appendToBody"
> >                 size="medium"
> >                 v-model="checkedSubjects">
> > </el-multi-cascader>
> > ```
> > 
> > 
> > ```js
> >       appendToBody: true,
> >       multiple: true,
> >       selectChildren: false,
> >       onlyOutPutLeafNode: false,
> >       collapseTags: false,
> >       filterable: false,
> >       showAllLevels: false,
> >       expandTrigger: 'hover',
> >       separator: '-',
> >       disabled: false,
> >       clearable: true,
> >       changeOnSelect: true
> > ```
> > 
> > 
> > 出现了描述中的问题
> > ![image](https://user-images.githubusercontent.com/17507451/68357269-b80b1680-014f-11ea-8f38-f08940f8f101.png)
> > 在设置showAllLevels为true后，就没有这个问题了，但是需要的是只显示选择的一级。
> 
> https://zhenyucheng.github.io/multiCascaderBaseEle/dist/index.html example中并没有复现这个问题？是否有Demo或者复现步骤？

![重现步骤](https://user-images.githubusercontent.com/17507451/68829635-4b11f680-06e4-11ea-93e1-b11c04d30005.gif)
可能我的描述不太准确，这个重现步骤应该可以说明问题。感谢你的回复。

**Comment by ZhenyuCheng** [comment]
> > > ```
> > > <el-multi-cascader
> > >                 ref="subject"
> > >                 class="l-d-no-border"
> > >                 style="width: 100%;"
> > >                 :placeholder="placeholder"
> > >                 :options="options"
> > >                 multiple
> > >                 :select-children="selectChildren"
> > >                 :only-out-put-leaf-node="onlyOutPutLeafNode"
> > >                 :collapse-tags="collapseTags"
> > >                 :filterable="filterable"
> > >                 :show-all-levels="showAllLevels"
> > >                 :expand-trigger="expandTrigger"
> > >                 :separator="separator"
> > >                 :disabled="disabled"
> > >                 @change="valueChange"
> > >                 :clearable="clearable"
> > >                 :change-on-select="changeOnSelect"
> > >                 :append-to-body="appendToBody"
> > >                 size="medium"
> > >                 v-model="checkedSubjects">
> > > </el-multi-cascader>
> > > ```
> > > 
> > > 
> > > ```js
> > >       appendToBody: true,
> > >       multiple: true,
> > >       selectChildren: false,
> > >       onlyOutPutLeafNode: false,
> > >       collapseTags: false,
> > >       filterable: false,
> > >       showAllLevels: false,
> > >       expandTrigger: 'hover',
> > >       separator: '-',
> > >       disabled: false,
> > >       clearable: true,
> > >       changeOnSelect: true
> > > ```
> > > 
> > > 
> > > 出现了描述中的问题
> > > ![image](https://user-images.githubusercontent.com/17507451/68357269-b80b1680-014f-11ea-8f38-f08940f8f101.png)
> > > 在设置showAllLevels为true后，就没有这个问题了，但是需要的是只显示选择的一级。
> > 
> > 
> > https://zhenyucheng.github.io/multiCascaderBaseEle/dist/index.html example中并没有复现这个问题？是否有Demo或者复现步骤？
> 
> ![重现步骤](https://user-images.githubusercontent.com/17507451/68829635-4b11f680-06e4-11ea-93e1-b11c04d30005.gif)
> 可能我的描述不太准确，这个重现步骤应该可以说明问题。感谢你的回复。

已于1.0.28版本修复 #
