### ISSUE TITLE
你这里好像并不能设置 initialInputHeight 的值，导致默认高度总是40

### ISSUE THREAD

**Issue by helloli** [ZhenyuCheng/multiCascaderBaseEle#2]
https://github.com/ZhenyuCheng/multiCascaderBaseEle/blob/1effa967ba8c4fa43ad8936b4331d6aff355ca11/multiCascader/src/main.vue#L606

**Comment by ZhenyuCheng** [comment]
已修正

**Comment by helloli** [comment]
可用了，谢谢，反应很快呀
