### ISSUE TITLE
请问能添加默认选择吗

### ISSUE THREAD

**Issue by msisliao** [ZhenyuCheng/multiCascaderBaseEle#4]
我加上默认选择报错：selectedOptions:["1","11","51"]

**Comment by so-hhh** [comment]
> 我加上默认选择报错：selectedOptions：[ “1”， “11”， “51”]

请问你处理好了吗？

**Comment by msisliao** [comment]
没有啊~~

**Comment by msisliao** [comment]
> > 我加上默认选择报错：selectedOptions：[ “1”， “11”， “51”]
> 
> 请问你处理好了吗？

没有啊

**Comment by ZhenyuCheng** [comment]
> 我加上默认选择报错：selectedOptions:["1","11","51"]

我自己加默认选择没有问题额，有错误的demo代码吗，你可以先确认下id是否唯一，还有你options里面对应的值类型，是否跟你传入默认值的类型是一样的，一边字符串，一边Number是不行的

**Comment by msisliao** [comment]
> > 我加上默认选择报错：selectedOptions:["1","11","51"]
> 
> 我自己加默认选择没有问题额，有错误的demo代码吗，你可以先确认下id是否唯一，还有你options里面对应的值类型，是否跟你传入默认值的类型是一样的，一边字符串，一边Number是不行的

呃呃 ，我把selectedOptions这个打印出来了，发现他的值是数组包含数组，
所以selectedOptions:[["1","11","51"]] 这样是正确的，
我还想请教个问题，能把下拉菜单直接展示在页面上吗？还有就是能默认展示N级吗(现在默认只有一级，点击才会展示下一级)？

**Comment by so-hhh** [comment]
我想问一下，我做的是弹出层里面嵌套的这个，可是我点击之后他会被原来的弹出层给覆盖住，这是因为什么呢？
![image](https://user-images.githubusercontent.com/45731612/57203600-14944a00-6fe4-11e9-9b82-8908c83e062a.png)

**Comment by msisliao** [comment]
> 我想问一下，我做的是弹出层里面嵌套的这个，可是我点击之后他会被原来的弹出层给覆盖住，这是因为什么呢？
> ![image](https://user-images.githubusercontent.com/45731612/57203600-14944a00-6fe4-11e9-9b82-8908c83e062a.png)

感觉demo还有点问题，如果设置了一个默认值有三级,那么第一次打开下拉菜单应该直接展示1、2、3级，现在只是展示了第一级

**Comment by msisliao** [comment]
> > 我想问一下，我做的是弹出层里面嵌套的这个，可是我点击之后他会被原来的弹出层给覆盖住，这是因为什么呢？
> > ![image](https://user-images.githubusercontent.com/45731612/57203600-14944a00-6fe4-11e9-9b82-8908c83e062a.png)
> 
> 感觉demo还有点问题，如果设置了一个默认值有三级,那么第一次打开下拉菜单应该直接展示1、2、3级，现在只是展示了第一级

盖住问题一般是定位跟z-index，你把弹框层设置小些，然后引入的这个组件设大点

**Comment by ZhenyuCheng** [comment]
> > > 我加上默认选择报错：selectedOptions:["1","11","51"]
> > 
> > 
> > 我自己加默认选择没有问题额，有错误的demo代码吗，你可以先确认下id是否唯一，还有你options里面对应的值类型，是否跟你传入默认值的类型是一样的，一边字符串，一边Number是不行的
> 
> 呃呃 ，我把selectedOptions这个打印出来了，发现他的值是数组包含数组，
> 所以selectedOptions:[["1","11","51"]] 这样是正确的，
> 我还想请教个问题，能把下拉菜单直接展示在页面上吗？还有就是能默认展示N级吗(现在默认只有一级，点击才会展示下一级)？

每一级的浮层是复用的，前一级活跃的item确定了下一级才能确定展示什么，单选的时候直接展示到默认值对应的级数目前是可以的，但是多选的时并不能确认当前活跃的是哪个菜单，所以是不支持的, 
如果需要的话可以我可以加一个属性，用来在多选的时候指定初次加载时要激活的浮层路径

**Comment by ZhenyuCheng** [comment]
> 我想问一下，我做的是弹出层里面嵌套的这个，可是我点击之后他会被原来的弹出层给覆盖住，这是因为什么呢？
> ![image](https://user-images.githubusercontent.com/45731612/57203600-14944a00-6fe4-11e9-9b82-8908c83e062a.png)
你可以按照msisliao所说的  调整复写z-index让浮层的z-index更高，或者dialog更低，
个人推荐使用图中的append-to-body属性来实现，设置:append-to-body="false"  parent-el="元素选择器"来指定组件挂载的父元素，来解决定位问题
![image](https://user-images.githubusercontent.com/16819722/57205482-89ba4c00-6ff1-11e9-8d64-492d77d868fc.png

![image](https://user-images.githubusercontent.com/16819722/57205470-71e2c800-6ff1-11e9-9d54-dd6843d3e4fd.png)

**Comment by so-hhh** [comment]
非常感谢大佬，因为初学element-ui，所以很多坑，感谢

**Comment by ZhenyuCheng** [comment]
> > 我想问一下，我做的是弹出层里面嵌套的这个，可是我点击之后他会被原来的弹出层给覆盖住，这是因为什么呢？
> > ![image](https://user-images.githubusercontent.com/45731612/57203600-14944a00-6fe4-11e9-9b82-8908c83e062a.png)
> 
> 感觉demo还有点问题，如果设置了一个默认值有三级,那么第一次打开下拉菜单应该直接展示1、2、3级，现在只是展示了第一级

已添加属性currentActiveValue，用于指定初次加载展开菜单路径

**Comment by msisliao** [comment]
> > > 我想问一下，我做的是弹出层里面嵌套的这个，可是我点击之后他会被原来的弹出层给覆盖住，这是因为什么呢？
> > > ![image](https://user-images.githubusercontent.com/45731612/57203600-14944a00-6fe4-11e9-9b82-8908c83e062a.png)
> > 
> > 
> > 感觉demo还有点问题，如果设置了一个默认值有三级,那么第一次打开下拉菜单应该直接展示1、2、3级，现在只是展示了第一级
> 
> 已添加属性currentActiveValue，用于指定初次加载展开菜单路径

大佬啊，大神啊，如果想直接在页面展示四级菜单，没有点一下才出来的，应该怎么弄啊？？

**Comment by ZhenyuCheng** [comment]
> > > > 我想问一下，我做的是弹出层里面嵌套的这个，可是我点击之后他会被原来的弹出层给覆盖住，这是因为什么呢？
> > > > ![image](https://user-images.githubusercontent.com/45731612/57203600-14944a00-6fe4-11e9-9b82-8908c83e062a.png)
> > > 
> > > 
> > > 感觉demo还有点问题，如果设置了一个默认值有三级,那么第一次打开下拉菜单应该直接展示1、2、3级，现在只是展示了第一级
> > 
> > 
> > 已添加属性currentActiveValue，用于指定初次加载展开菜单路径
> 
> 大佬啊，大神啊，如果想直接在页面展示四级菜单，没有点一下才出来的，应该怎么弄啊？？

挂一个ref，然后调用内部方法就行
this.$refs.multiBranch.handleClick()  展开
this.$refs.multiBranch.handleClickoutside() 隐藏
