### ISSUE TITLE
组件console.log没有去除；监听change事件，选择一项会触发多次

### ISSUE THREAD

**Issue by fanwenlie** [ZhenyuCheng/multiCascaderBaseEle#5]
##### 1. menu组件：console.log没有去除
![image](https://user-images.githubusercontent.com/23098332/57689113-8407da80-7671-11e9-9cab-a714169bfb0d.png)

##### 2. 监听change事件，选择一项会触发多次

![image](https://user-images.githubusercontent.com/23098332/57689461-2627c280-7672-11e9-9ea1-a93a9c78a891.png)

**Comment by fox19920726** [comment]
+1

**Comment by ZhenyuCheng** [comment]
> ##### 1. menu组件：console.log没有去除
> ![image](https://user-images.githubusercontent.com/23098332/57689113-8407da80-7671-11e9-9cab-a714169bfb0d.png)
> 
> ##### 2. 监听change事件，选择一项会触发多次
> ![image](https://user-images.githubusercontent.com/23098332/57689461-2627c280-7672-11e9-9ea1-a93a9c78a891.png)

感谢指出，1.0.18版本已修复，最近业务比较忙，没怎么看~
