### ISSUE TITLE
异步获取数据报错问题

### ISSUE THREAD

**Issue by marinLu** [ZhenyuCheng/multiCascaderBaseEle#6]

**Comment by ZhenyuCheng** [comment]
具体描述下？

**Comment by marinLu** [comment]
获取dom元素会报错发自我的华为手机-------- 原始邮件 --------主题：Re: [ZhenyuCheng/multiCascaderBaseEle] 异步获取数据报错问题 (#6)发件人：程震宇 收件人：ZhenyuCheng/multiCascaderBaseEle 抄送：Lucus ,Author 具体描述下？



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ZhenyuCheng/multiCascaderBaseEle/issues/6?email_source=notifications\u0026email_token=AHA45KAHIYOTUKIHOTUOJ33PWKUMDA5CNFSM4HNRTIQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVY4WWQ#issuecomment-493996890",

"url": "https://github.com/ZhenyuCheng/multiCascaderBaseEle/issues/6?email_source=notifications\u0026email_token=AHA45KAHIYOTUKIHOTUOJ33PWKUMDA5CNFSM4HNRTIQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVY4WWQ#issuecomment-493996890",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ZhenyuCheng** [comment]
> 获取dom元素会报错发自我的华为手机-------- 原始邮件 --------主题：Re: [ZhenyuCheng/multiCascaderBaseEle] 异步获取数据报错问题 (#6)发件人：程震宇 收件人：ZhenyuCheng/multiCascaderBaseEle 抄送：Lucus ,Author 具体描述下？ —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#6?email_source=notifications\u0026email_token=AHA45KAHIYOTUKIHOTUOJ33PWKUMDA5CNFSM4HNRTIQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVY4WWQ#issuecomment-493996890", "url": "#6?email_source=notifications\u0026email_token=AHA45KAHIYOTUKIHOTUOJ33PWKUMDA5CNFSM4HNRTIQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVY4WWQ#issuecomment-493996890", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

你是怎么获取的，有代码片段吗~
