### ISSUE TITLE
清除的问题

### ISSUE THREAD

**Issue by so-hhh** [ZhenyuCheng/multiCascaderBaseEle#7]
在我修改赋上默认值后，必须得让他获取到焦点才能单个清除，不然的话就会出现异常，我试过给他一开始进入的时候默认赋上焦点，可是在这里是赋不上的
![image](https://user-images.githubusercontent.com/45731612/58064531-0eda5f00-7bb5-11e9-80a9-bdb98256a724.png)

**Comment by ZhenyuCheng** [comment]
的确有这个问题，原因是弹出框没有初始化，已修复

**Comment by so-hhh** [comment]
那我用的你之前的代码如何做到弹出层初始化呢？

**Comment by so-hhh** [comment]
谢谢了，已经解决了，感谢

**Comment by so-hhh** [comment]
我重新导入了依赖，单个清除是没有问题了，可是在选择的时候出现了很大问题
在选择时出现报错，我这拉下来您的依赖是有什么错误吗？
![0fd6b845deb9beaaf2550eda6dca7fa4](https://user-images.githubusercontent.com/45731612/58082206-1d426e00-7be9-11e9-9ab7-720ac003307c.jpg)

**Comment by so-hhh** [comment]
您好，您可以留一个联系方式吗？可以的话我给您发一段视频，感谢大佬帮助

**Comment by ZhenyuCheng** [comment]
> 您好，您可以留一个联系方式吗？可以的话我给您发一段视频，感谢大佬帮助

图片看不清楚，可以发这个邮箱chengzhenyu925@163.com
最好能提一个报错的demo的jsfiddle 或者codepen~~
